/**
 * Every rejection reason the engine can produce. Codes are stable strings so the
 * frontend can map them to messages without parsing prose.
 */
export const ERRORS = {
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',

  // Turn / phase
  GAME_NOT_PLAYING: 'GAME_NOT_PLAYING',
  NOT_YOUR_TURN: 'NOT_YOUR_TURN',
  UNKNOWN_PLAYER: 'UNKNOWN_PLAYER',
  UNKNOWN_ACTION: 'UNKNOWN_ACTION',

  // Discard phase
  DISCARD_REQUIRED: 'DISCARD_REQUIRED',
  NO_DISCARD_PENDING: 'NO_DISCARD_PENDING',
  DISCARD_WRONG_AMOUNT: 'DISCARD_WRONG_AMOUNT',
  DISCARD_TOKENS_NOT_HELD: 'DISCARD_TOKENS_NOT_HELD',

  // Taking tokens
  INVALID_COLOR: 'INVALID_COLOR',
  NEED_THREE_DISTINCT_COLORS: 'NEED_THREE_DISTINCT_COLORS',
  COLOR_NOT_AVAILABLE: 'COLOR_NOT_AVAILABLE',
  NOT_ENOUGH_IN_BANK_FOR_TWO: 'NOT_ENOUGH_IN_BANK_FOR_TWO',

  // Reserving
  RESERVE_LIMIT_REACHED: 'RESERVE_LIMIT_REACHED',
  DECK_EMPTY: 'DECK_EMPTY',
  CARD_NOT_ON_TABLE: 'CARD_NOT_ON_TABLE',
  INVALID_TIER: 'INVALID_TIER',

  // Buying
  CARD_NOT_FOUND: 'CARD_NOT_FOUND',
  CARD_NOT_RESERVED: 'CARD_NOT_RESERVED',
  INSUFFICIENT_RESOURCES: 'INSUFFICIENT_RESOURCES',
} as const;

export type ErrorCode = (typeof ERRORS)[keyof typeof ERRORS];
